### ISSUE TITLE
Download wrapper requires Moodle 3.11

### ISSUE THREAD

**Issue by leonstr** [catalyst/moodle-mod_scormremote#43]
Version information says mod_scormremote supports Moodle 3.9 to 4.0. But `mod_scormremote\packagefile->download_wrapper()` uses `core_files\archive_writer` which was introduced in Moodle 3.11 (MDL-68533).

Consequently clicking the _Download_ button on `mod/scormremote/wrapper.php?cmid=<ID>` with Moodle 3.9 results in:

```
Exception - Class 'core_files\archive_writer' not found

More information about this error
Debug info:
Error code: generalexceptionmessage
Stack trace:

    line 139 of /mod/scormremote/classes/packagefile.php: Error thrown
    line 92 of /mod/scormremote/wrapper.php: call to mod_scormremote\packagefile::download_wrapper()
```

**Comment by andrewhancox** [comment]
See fix:
https://github.com/andrewhancox/moodle-mod_scormremote/tree/39_compatible

**Comment by bwalkerl** [comment]
Should be resolved with https://github.com/catalyst/moodle-mod_scormremote/commit/c794e394a40521900325fe632b3186fdb64abe3f
