### ISSUE TITLE
Implement data privacy provider

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-mod_scormremote#5]
This does record data from it doesn't send it anywhere, it is import only from the other site. So I think technically this doesn't store user data even though it does.

I think the best next option is to implement it in a way that allows an admin to login as to this person and make data requests on behalf of that person. Or if the psuedo users ever get turned into real accounts then it will magically just work.

Tasks:
* [ ] implement a privacy provider that behaves correctly if somebody does a login as to the fake user
* [ ] or same same - if the user is converted from a fake user into a real manual account

**Comment by danmarsden** [comment]
note this is a plugins db approval blocker when a plugin commiunicates with an external "thing/api" - which I think includes this plugin so it's probably also a blocker for approval.
