### ISSUE TITLE
README says Moodle stores completion status?

### ISSUE THREAD

**Issue by leonstr** [catalyst/moodle-mod_scormremote#55]
The README says _As learners on the remote site use the scorm, you will see accounts created in your Moodle and enrolments and **completion status for those accounts**_. I want to make sure I understand the plugin's functionality and I don't think that's correct. Is there completion tracking of remote learners on the hosting Moodle?

Or is this an error in the README?

(Also asked [this question on the plugin comments page](https://moodle.org/plugins/mod_scormremote#comment-79650-651c1b0ab302d)).

**Comment by danmarsden** [comment]
yes - that's the whole point - being able to track user completion in both places (the external LMS) but also your existing Moodle.

**Comment by leonstr** [comment]
mod_scormremote's _Completion tracking_ setting has two options: "Students can manually mark the activity as completed" and "Do not indicate activity completion". Obviously only the former results in the activity appearing at all in the activity completion report (`report/progress/index.php?course=ID`). In my tests this only ever shows _Not completed_, whereas on the remote site (with the wrapper) the student has completed the activity.

mod_scormremote 2023070600 on Moodle 4.1.5+ (Build: 20230929).

**Comment by leonstr** [comment]
Looking into this further I don't think the Moodle-side completion tracking works: #56.
