### ISSUE TITLE
Completion status not updated in Moodle

### ISSUE THREAD

**Issue by leonstr** [catalyst/moodle-mod_scormremote#56]
If a remote student completes the SCORM, on the Moodle site their completion status is not set to "Completed".

This appears to be because `submit_completion.php` has `require_login(0, false)` so the POST /mod/scormremote/submit_completion.php gets 303 See Other: /login/index.php.

mod_scormremote 2023070600 with Moodle 4.1.5+ (Build: 20230929).

**Comment by sharon-wetzig** [comment]
This is an issue for us currently. Some student completion data is recorded but not all - does this rely on students in the remote site 'marking as done' or whatever manual completion recording the remote LMS has set up?
