### ISSUE TITLE
Not compatible with 3.9

### ISSUE THREAD

**Issue by andrewhancox** [catalyst/moodle-mod_scormremote#61]
The MOODLE_39_STABLE is not actually compatible with Moodle 3.9 as it depends on core_files\archive_writer

I've pushed a version that works to https://github.com/andrewhancox/moodle-mod_scormremote/tree/39_compatible

**Comment by leonstr** [comment]
Duplicate of [#43](https://github.com/catalyst/moodle-mod_scormremote/issues/43).
